// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfhenndnrbbvlwengrtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmaGVubmRucmJidmx3ZW5ncnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDY0NzMsImV4cCI6MjA2ODAyMjQ3M30.81fGPEEn9ECcUXGsb_VfwH_ImpI1myAGq0LAGytDycY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});